version: '3'
services:
  m3u-filter:
    container_name: m3u-filter
    image: docker.io/mikmc/m3u-filter:latest
    working_dir: /
    volumes:
      - ./data:/data
      - ./config:/config
      - ./backup:/backup
      - ./downloads:/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
